const CHARACTERS = [
  "Bazaar Owner",
  "Bean Seller",
  "Beggar",
  "Biggoron",
  "Bomb Shop Owner",
  "Bombchu Bowling Alley Operator",
  "Bonooru",
  "Carpenters",
  "Carpet Merchant",
  "Cucco Lady",
  "Dampé",
  "Dancing Couple",
  "Darunia",
  "Death Mountain Trail Guard",
  "Deku Tree Sprout",
  "Epona",
  "Fabulous Five Froggish Tenors",
  "Fado",
  "Fishing Hole Man",
  "Flat",
  "Ganondorf",
  "Granny",
  "Graveyard Boy",
  "Great Deku Tree",
  "Great Fairy",
  "Grog",
  "Guards",
  "Guru-Guru",
  "Happy Mask Salesman",
  "Hot Rodder Goron",
  "Impa",
  "Ingo",
  "Kaepora Gaebora",
  "King Zora",
  "Know-It-All Brothers",
  "Lake Scientist",
  "Laughing Man",
  "Link (Goron)",
  "Link",
  "Lord Jabu-Jabu",
  "Malon",
  "Mamamu Yan",
  "Man on a Roof",
  "Marathon Man",
  "Medicine Shop Owner",
  "Medigoron",
  "Mido",
  "Nabooru",
  "Nabooru's Second-in-Command",
  "Navi",
  "Old Man",
  "Pierre",
  "Poe Collector",
  "Princess Ruto",
  "Princess Zelda",
  "Rauru",
  "Rich Family from the house of Skulltula",
  "Sakon",
  "Saria",
  "Sharp",
  "Sheik",
  "Shooting Gallery Owner",
  "Talon",
  "Twinrova",
  "Wounded Soldier"
];

export default CHARACTERS;
